#!/bin/bash
# 打印的文字颜色
RED='\033[0;31m'
GREEN='\033[0;32m'
default='\033[0m'
printf "+----------------------------------------------------------------------------------------------------------------+
"
printf "${GREEN}目录说明:${default}
"
printf "╔═════════════════╦════════╦════╦═════════════════════════════════════════════════════════════════════════╗
"
printf "║目录             ║名称    ║速度║说明                                                                     ║
"
printf "╠═════════════════╬════════╬════╬═════════════════════════════════════════════════════════════════════════╣
"
printf "║/                ║系 统 盘║一般║实例关机数据不会丢失，可存放代码等。会随保存镜像一起保存。               ║
"
printf "╚═════════════════╩════════╩════╩═════════════════════════════════════════════════════════════════════════╝
"

if test -f "/sys/fs/cgroup/cpu/cpu.cfs_quota_us"; then
  cfs_quota_us=$(cat /sys/fs/cgroup/cpu/cpu.cfs_quota_us)
  cfs_period_us=$(cat /sys/fs/cgroup/cpu/cpu.cfs_period_us)
  if [ $cfs_quota_us -ge $cfs_period_us ];then
      cores=$((cfs_quota_us / cfs_period_us))
  else
      cores=0.$((cfs_quota_us * 10 / cfs_period_us))
  fi
  printf "${GREEN}CPU${default} ：%s 核
" ${cores}

  limit_in_bytes=$(cat /sys/fs/cgroup/memory/memory.limit_in_bytes)
  memory="$((limit_in_bytes / 1024 / 1024 / 1024)) GB"
  printf "${GREEN}内存${default}：%s
" "${memory}"
else
  cores=$(cat /sys/fs/cgroup/cpu.max | awk '{print $1/$2}')
  printf "${GREEN}CPU${default} ：%s 核
" ${cores}

  limit_in_bytes=$(cat /sys/fs/cgroup/memory.max)
  memory="$((limit_in_bytes / 1024 / 1024 / 1024)) GB"
  printf "${GREEN}内存${default}：%s
" "${memory}"
fi

if type nvidia-smi >/dev/null 2>&1; then
  gpu=$(nvidia-smi -i 0 --query-gpu=name,count --format=csv,noheader)
  printf "${GREEN}GPU${default} ：%s
" "${gpu}"
fi

df_stats=`df -ah`
printf "${GREEN}存储${default}：
"
disk=$(echo "$df_stats" | grep "/$" | awk '{print $5" "$3"/"$2}')
printf "  ${GREEN}/${default}               ：%s
" "${disk}"


printf "+----------------------------------------------------------------------------------------------------------------+
"
printf "${RED}*注意: 
"
printf "${RED}1.清理系统盘请参考文档${default}
"

alias sudo=""
