ARG BASE_IMAGE

FROM ${BASE_IMAGE}

# install vllm-cuda
ARG VLLM_VERSION
RUN pip --no-cache-dir install vllm==${VLLM_VERSION}

ADD --chown=ray:users https://raw.githubusercontent.com/ray-project/kuberay/refs/tags/v1.2.1/ray-operator/config/samples/vllm/serve.py /home/ray/serve.py
