ARG BASE_IMAGE

FROM ${BASE_IMAGE}

# 安装常用依赖，torch和tensorflow提供不同的镜像
RUN pip --no-cache-dir install \
      mpmath==1.3.0 \
      sympy==1.13.1 \
      torch==2.3.0 \
      torchaudio==2.3.0 \
      torchvision==0.18.0 \
      --index-url https://download.pytorch.org/whl/cu124
